### ISSUE TITLE
 I can't find the .vsto file to install, where is it？

### ISSUE THREAD

**Issue by fengshansi** [dinhngtu/OutlookCloseToMinimize#3]
![image](https://user-images.githubusercontent.com/50689156/137632246-5a278adc-1279-437b-b027-067391c17453.png)
This is the dictionary, and I can't find the .vsto file. 
I installed the VSTO runtime. Do I need to download the visual studio？

**Comment by dinhngtu** [comment]
Hi, you need to build the project to get the .vsto output file. I only tested building the project with Visual Studio but haven't tried other IDEs.

You can get a prebuilt version here: https://github.com/dinhngtu/OutlookCloseToMinimize/releases/tag/1.3
