### ISSUE TITLE
The program not working, When I press close/x it does not minimize but closes outlook.

### ISSUE THREAD

**Issue by bigplayer-ai** [dinhngtu/OutlookCloseToMinimize#5]
The program not working, When I press close/x it does not minimize but closes outlook.

**Comment by dinhngtu** [comment]
Which version of the addin are you using? Could you try uninstalling all existing versions and installing the latest one ([version 1.4.4](https://github.com/dinhngtu/OutlookCloseToMinimize/releases/tag/1.4.4)) again?

If it still doesn't work, could you try applying this file: [forceload.reg](https://github.com/dinhngtu/OutlookCloseToMinimize/blob/master/forceload.reg)

**Comment by bigplayer-ai** [comment]
Uninstalling all versions and reinstalling fixed the issue.
Thanks
